# Generated by Django 3.0.4 on 2020-04-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_topic_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='removed_by_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
