# Generated by Django 3.0.4 on 2020-04-07 14:19

from django.db import migrations, models
import users.helpers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200407_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/default.jpg', null=True, upload_to=users.helpers.helpers.user_directory_path),
        ),
    ]
