# Generated by Django 3.0.4 on 2020-04-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
