# Generated by Django 3.0.4 on 2020-04-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userteamrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='blood_coins',
            new_name='coins',
        ),
    ]
