version: "3"

services:
  redis:
    image: "redis:alpine"
    command: >
      redis-server --port 6380
  celery-beat:
    build: .
    env_file:
      - .env
    command: celery beat --app Forum.celery
    volumes:
      - ./backend:/backend
    depends_on:
      - db
      - redis
  celery:
    build: .
    env_file:
      - .env
    command: celery -A Forum worker -l info
    volumes:
      - ./backend:/backend
    depends_on:
      - db
      - redis
  backend:
    build:
      context: .
    restart: always
    ports:
    - "5000:5000"
    volumes:
    - ./backend:/backend
    command: sh -c "rm -rf celerybeat.pid && python manage.py migrate && python manage.py runserver 0.0.0.0:5000"
    env_file:
      - .env
    depends_on:
      - db
      - celery-beat
      - celery
  frontend:
    image: node:13.10.1-stretch
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
    - ./backend/static/frontend:/frontend
    working_dir: /frontend
    command: bash -c "npm install && npm run dev"
    depends_on:
      - backend

  db:
    image: postgres:12.1-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200/
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.6.0
    volumes:
      - .:/logstash/
    ports:
      - "5959:5959"
    command: logstash -f /logstash/logstash/config/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
  ngrok:
    image: wernight/ngrok
    depends_on:
      - backend
    env_file:
      - ./ngrok/.env
    ports:
      - 4040:4040
volumes:
  elasticsearchdata:
    driver: local
  db-data: