version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "3060:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  redis:
    container_name: redis
    image: "redis:alpine"
    command: >
      redis-server --port 6380
  celery-beat:
    container_name: celery-beat
    build: .
    env_file:
      - .env
    command: celery beat --app Forum.celery
    depends_on:
      - db
      - redis
  celery:
    container_name: celery
    build: .
    env_file:
      - .env
    command: celery -A Forum worker -l info
    depends_on:
      - db
      - redis
  backend:
    container_name: backend
    build:
      context: .
    restart: always
    command: sh -c "rm -rf celerybeat.pid && python manage.py migrate && gunicorn Forum.wsgi:application --bind 0.0.0.0:5000"
    env_file:
      - .env
    depends_on:
      - db
      - celery-beat
      - celery
  frontend:
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: ./frontend
    restart: always
    depends_on:
      - backend
  db:
    container_name: db
    image: postgres:12.1-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env
volumes:
  db-data: