version: "3"

services:
  redis:
    image: "redis:alpine"
    command: >
      redis-server --port 6380
  celery-beat:
    build: .
    env_file:
      - .env
    command: celery beat --app Forum.celery
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
  celery:
    build: .
    env_file:
      - .env
    command: celery -A Forum worker -l info
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
  backend:
    build:
      context: .
    restart: always
    ports:
    - 5000:5000
    command: sh -c "rm -rf celerybeat.pid && python manage.py migrate && gunicorn Forum.wsgi:application --bind 0.0.0.0:5000"
    env_file:
      - .env
    depends_on:
      - db
      - celery-beat
      - celery
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    restart: always
    ports:
      - 8080:80
    depends_on:
      - backend
  db:
    image: postgres:12.1-alpine
    env_file:
      - .env
volumes:
  db-data:
