version: "3"

services:
  redis:
    image: "redis:alpine"
    command: >
      redis-server --port 6380
  celery-beat:
    build: .
    env_file:
      - .env
    command: celery beat --app Forum.celery
    volumes:
      - ./forum:/forum
    depends_on:
      - db
      - redis
  celery:
    build: .
    env_file:
      - .env
    command: celery -A Forum worker -l info
    volumes:
      - ./forum:/forum
    depends_on:
      - db
      - redis
  backend:
    build:
      context: .
    restart: always
    ports:
    - "5000:5000"
    volumes:
    - ./forum:/forum
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:5000"
    env_file:
      - .env
    depends_on:
      - db
      - celery-beat
      - celery
  frontend:
    image: node:13.10.1-stretch
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
    - ./forum/static/frontend:/frontend
    working_dir: /frontend
    command: bash -c "npm install && npm run dev"
    depends_on:
      - backend

  db:
    image: postgres:12.1-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=forum
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  db-data: