# Generated by Django 3.0.4 on 2020-04-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200401_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-edited_at'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='icon',
        ),
        migrations.AlterField(
            model_name='topic',
            name='edited_at',
            field=models.DateTimeField(),
        ),
    ]
