# Generated by Django 3.0.4 on 2020-03-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200319_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='likes',
        ),
    ]
