# Generated by Django 3.0.4 on 2020-03-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200326_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='rating',
        ),
    ]
