# Generated by Django 3.0.4 on 2020-04-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200327_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
