# Generated by Django 3.0.4 on 2020-04-15 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import core.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'success'), (2, 'info'), (3, 'warning'), (4, 'danger')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, core.mixins.NotificationTextMixin),
        ),
    ]
