# Generated by Django 3.0.4 on 2020-04-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='notification_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'success'), (2, 'info'), (3, 'warning'), (4, 'error')], null=True),
        ),
    ]
