# Generated by Django 3.0.4 on 2020-04-27 07:35

from django.db import migrations, models
import users.helpers.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rank_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.helpers.helpers.user_directory_path),
        ),
        migrations.AlterUniqueTogether(
            name='rank',
            unique_together={('team', 'name')},
        ),
    ]
